services:
  postgres:
    image: postgres:15
    container_name: credit_scoring_postgres
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow
      POSTGRES_DB: mlflow
    ports:
      - "55432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: credit_scoring_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  create-minio-bucket:
    image: minio/mc:latest
    container_name: credit_scoring_create_bucket
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set local http://minio:9000 minio minio123;
      mc mb -p local/mlflow;
      exit 0;
      "

  mlflow:
    image: python:3.11-slim
    container_name: credit_scoring_mlflow
    depends_on:
      - postgres
      - minio
      - create-minio-bucket
    environment:
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: minio123
    ports:
      - "5000:5000"
    command: >
      /bin/sh -c "
      pip install mlflow boto3 psycopg2-binary &&
      mlflow server
      --backend-store-uri postgresql://mlflow:mlflow@postgres:5432/mlflow
      --default-artifact-root s3://mlflow/
      --host 0.0.0.0
      --port 5000
      --allowed-hosts 'localhost:*,127.0.0.1:*,mlflow:5000,credit_scoring_mlflow:5000'
      --cors-allowed-origins 'http://localhost:*,http://127.0.0.1:*'
      "
      
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: credit_scoring_api
    depends_on:
      - mlflow
      - minio
      - postgres
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: minio123
      DATABASE_URL: postgresql+psycopg2://mlflow:mlflow@postgres:5432/mlflow
    ports:
      - "8000:8000"

  prometheus:
    image: prom/prometheus:latest 
    container_name: credit_scoring_prometheus
    depends_on:
      - api
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: credit_scoring_grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - ./monitoring/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./monitoring/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards

  airflow-init:
    image: apache/airflow:2.10.4-python3.11
    container_name: credit_scoring_airflow_init
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://mlflow:mlflow@postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__SECRET_KEY: credit-scoring-secret
      MLFLOW_TRACKING_URI: http://mlflow:5000
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: minio123
      DATABASE_URL: postgresql+psycopg2://mlflow:mlflow@postgres:5432/mlflow
    volumes:
      - ./:/opt/airflow/project
      - ./dags:/opt/airflow/dags
    command: >
      bash -c "
      pip install -r /opt/airflow/project/requirements-airflow.txt &&
      airflow db upgrade &&
      airflow users create
      --username admin
      --password admin
      --firstname Admin
      --lastname User
      --role Admin
      --email admin@example.com
      "

  airflow-webserver:
    image: apache/airflow:2.10.4-python3.11
    container_name: credit_scoring_airflow_webserver
    depends_on:
      - airflow-init
      - postgres
      - mlflow
      - minio
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://mlflow:mlflow@postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__SECRET_KEY: credit-scoring-secret
      MLFLOW_TRACKING_URI: http://mlflow:5000
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: minio123
      DATABASE_URL: postgresql+psycopg2://mlflow:mlflow@postgres:5432/mlflow
    ports:
      - "8080:8080"
    volumes:
      - ./:/opt/airflow/project
      - ./dags:/opt/airflow/dags
    command: >
      bash -c "
      pip install -r /opt/airflow/project/requirements-airflow.txt &&
      airflow webserver
      "

  airflow-scheduler:
    image: apache/airflow:2.10.4-python3.11
    container_name: credit_scoring_airflow_scheduler
    depends_on:
      - airflow-init
      - postgres
      - mlflow
      - minio
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://mlflow:mlflow@postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__SECRET_KEY: credit-scoring-secret
      MLFLOW_TRACKING_URI: http://mlflow:5000
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: minio123
      DATABASE_URL: postgresql+psycopg2://mlflow:mlflow@postgres:5432/mlflow
    volumes:
      - ./:/opt/airflow/project
      - ./dags:/opt/airflow/dags
    command: >
      bash -c "
      pip install -r /opt/airflow/project/requirements-airflow.txt &&
      airflow scheduler
      "

volumes:
  postgres_data:
  minio_data:
