FROM apache/airflow:2.10.4-python3.11

USER root

RUN apt-get update && \
    apt-get install -y --no-install-recommends libgomp1 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

USER airflow

COPY requirements-airflow.txt /requirements-airflow.txt

RUN pip install --upgrade pip && \
    pip install --no-cache-dir --default-timeout=9000 --retries=20 -r /requirements-airflow.txt
