"""Read-only monitoring tools used by AI Engineering agents."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any


class MonitoringTools:
    """Expose safe read-only access to existing monitoring artifacts."""

    def __init__(self, signal_path: str | Path = "reports/retrain_signal.json") -> None:
        self.signal_path = Path(signal_path)

    def get_retrain_signal(self) -> dict[str, Any]:
        """Return the current retraining signal generated by the drift pipeline."""
        if not self.signal_path.exists():
            return {
                "available": False,
                "retrain_required": False,
                "reason": "Retrain signal file does not exist",
                "drifted_features": [],
            }

        try:
            with self.signal_path.open("r", encoding="utf-8") as file:
                signal = json.load(file)
        except (OSError, json.JSONDecodeError) as exc:
            return {
                "available": False,
                "retrain_required": False,
                "reason": f"Failed to read retrain signal: {exc}",
                "drifted_features": [],
            }

        return {
            "available": True,
            "retrain_required": bool(signal.get("retrain_required", False)),
            "reason": signal.get("reason", "Unknown"),
            "drifted_features": signal.get("drifted_features", []),
        }
